name: Geko
description: Stick to Adventure
version: 1.0.0

# Top-level environment constraint
environment:
  sdk: '^3.9.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  provider: ^6.0.5
  http: ^0.13.3
  flutter_dotenv: ^5.1.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/