name: geko
description: Stick to Adventure
version: 1.0.0

# Top-level environment constraint
environment:
  sdk: '^3.9.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  provider: ^6.0.5
  google_sign_in: ^6.2.5
  http: ^1.5.0
  flutter_dotenv: ^5.1.0
  flutter_map_marker_popup: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/